In [31]:
import pandas as pd

In [32]:
caramelo = pd.read_csv('CARAMELO.csv', sep= ';')
caramelo

,ID Venda,Loja,ID Loja,Estado Loja,Cidade Loja,Nome Cliente,ID Cliente,Sexo,Idade,Estado Cliente,Cidade Cliente,ID Produto,Categoria Produto,Marca,Data da Compra,Data da Entrega,Metodo de Pagamento,Produto,Valor de Venda
0,1,Melo,49,BA,Salvador,Lucas Silveira,35727,Masculino,24,BA,Vitória da Conquista,946,Eletrônicos,Lenovo,20/12/2024,30/12/2024,Pix,Drone,"7404,8"
1,10,Mendonça Machado Ltda.,7,SP,Sorocaba,Isabella Campos,2188,Feminino,41,MG,Uberlândia,112,Eletrônicos,Apple,22/11/2023,28/11/2023,Dinheiro,Celular,"2138,34"
2,1000,Cunha Mendes S.A.,97,BA,Camaçari,Marcela Barbosa,2293,Feminino,47,SP,Sorocaba,283,Alimentos,Del Valle,25/08/2023,27/08/2023,Dinheiro,Suco,"9,23"
3,100001,Nunes,77,MG,Contagem,Ravy Cunha,38559,Feminino,59,RJ,Petrópolis,805,Eletrônicos,Dell,03/08/2024,04/08/2024,Dinheiro,Notebook,"4178,61"
4,100007,Cunha Mendes S.A.,97,BA,Camaçari,Sra. Ana Cecília Pinto,19274,Masculino,27,SP,São Paulo,362,Alimentos,Coca-Cola,28/02/2023,08/03/2023,Pix,Refrigerante,"23,94"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149995,99992,Barbosa,96,RS,Pelotas,Caleb da Mota,223,Masculino,63,BA,Salvador,623,Alimentos,Pilão,11/11/2024,15/11/2024,Cartão,Café,"17,2"
149996,99994,Aparecida da Conceição e Filhos,15,RJ,Campos dos Goytacazes,Eduardo Cavalcanti,8975,Masculino,39,BA,Salvador,253,Alimentos,Vigorelli,11/01/2025,13/01/2025,Pix,Feijão,"42,23"
149997,99997,Moreira,53,RJ,Rio de Janeiro,Pedro Miguel Mendes,36587,Masculino,43,RS,Pelotas,535,Alimentos,Camil,09/09/2023,15/09/2023,Dinheiro,Arroz,"47,47"
149998,99998,Andrade,94,SP,Santos,Ana Luiza Porto,3938,Feminino,36,BA,Feira de Santana,183,Alimentos,Barilla,01/01/2025,02/01/2025,Pix,Macarrão,"30,37"
149999,99999,Teixeira,49,RS,Novo Hamburgo,Joana Moreira,11328,Feminino,24,BA,Feira de Santana,434,Roupas,Hering,05/09/2023,10/09/2023,Cartão,Camiseta,"284,43"

In [38]:
# vendas agrupadas pelo estado do Rio de Janeiro

df_Estado = caramelo.loc[caramelo['Cidade Loja'] == 'Rio de Janeiro']
df_Estado

,ID Venda,Loja,ID Loja,Estado Loja,Cidade Loja,Nome Cliente,ID Cliente,Sexo,Idade,Estado Cliente,Cidade Cliente,ID Produto,Categoria Produto,Marca,Data da Compra,Data da Entrega,Metodo de Pagamento,Produto,Valor de Venda
7,100012,Moreira,53,RJ,Rio de Janeiro,Sr. Gustavo Cavalcanti,27717,Masculino,62,BA,Salvador,286,Livros,Amazon,07/07/2025,09/07/2025,Cartão,A Revolução dos Bichos,"69,8"
8,100014,Moreira,53,RJ,Rio de Janeiro,Dr. Bruno Nunes,37283,Feminino,59,SP,Santos,615,Eletrônicos,Sony,08/06/2025,10/06/2025,Pix,Monitor,"1976,97"
15,100026,Moreira,53,RJ,Rio de Janeiro,Thiago da Mota,4856,Feminino,49,BA,Salvador,441,Móveis,Tramontina,30/12/2024,09/01/2025,Cartão,Poltrona,"2680,41"
21,100038,Moreira,53,RJ,Rio de Janeiro,Carolina Rezende,34771,Feminino,69,MG,Belo Horizonte,253,Alimentos,Vigorelli,18/07/2023,27/07/2023,Pix,Feijão,"26,17"
35,100063,Moreira,53,RJ,Rio de Janeiro,Luara Lopes,34748,Feminino,20,MG,Contagem,183,Alimentos,Barilla,01/10/2023,11/10/2023,Cartão,Macarrão,"20,98"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149974,99947,Vargas,11,RJ,Rio de Janeiro,Cauê Machado,28068,Masculino,46,BA,Camaçari,208,Eletrônicos,Sony,17/02/2024,20/02/2024,Pix,Console de Videogame,"2017,78"
149976,99951,Moreira,53,RJ,Rio de Janeiro,Helena da Cruz,22617,Feminino,20,MG,Juiz de Fora,825,Roupas,Lacoste,15/10/2023,16/10/2023,Cartão,Vestido,"271,37"
149977,99953,Sousa,50,RJ,Rio de Janeiro,Maysa Pires,20658,Feminino,63,SP,São Paulo,183,Alimentos,Barilla,28/02/2024,04/03/2024,Pix,Macarrão,41
149981,99963,Vargas,11,RJ,Rio de Janeiro,João Pedro Garcia,8494,Masculino,60,BA,Camaçari,623,Alimentos,Pilão,28/10/2023,31/10/2023,Cartão,Café,"44,77"
149997,99997,Moreira,53,RJ,Rio de Janeiro,Pedro Miguel Mendes,36587,Masculino,43,RS,Pelotas,535,Alimentos,Camil,09/09/2023,15/09/2023,Dinheiro,Arroz,"47,47"

In [48]:
# Tratamento de conversão de string numérica para float

caramelo['Valor de Venda'] = caramelo ['Valor de Venda'].str.replace(',','.').astype(float)

In [49]:
# vendas pelo método de pagamento 

df_Metodo_Pagamento = caramelo.groupby('Metodo de Pagamento')['Valor de Venda'].sum().reset_index()
df_Metodo_Pagamento

  Metodo de Pagamento  Valor de Venda
0              Cartão     62425052.73
1            Dinheiro     31829200.93
2                 Pix     62931250.96

In [51]:
# Vendas pelo de sexo 

df_Metodo_Pagamento = caramelo.groupby('Sexo')['Valor de Venda'].sum().reset_index()
df_Metodo_Pagamento

        Sexo  Valor de Venda
0   Feminino     82251600.73
1  Masculino     74933903.89

In [52]:
# Vendas por lojas 

df_Metodo_Pagamento = caramelo.groupby('Loja')['Valor de Venda'].sum().reset_index()
df_Metodo_Pagamento

                               Loja  Valor de Venda
0                           Andrade      6938690.85
1   Aparecida da Conceição e Filhos      9344661.45
2                           Barbosa      6539116.94
3                             Cunha      7335097.36
4                  Cunha Gomes - EI      7958426.67
5                 Cunha Mendes S.A.      6990635.97
6                         Fernandes      6746718.51
7                             Gomes      7780460.75
8                           Machado      8458472.88
9                              Melo      7486069.30
10           Mendonça Machado Ltda.      6821667.23
11                          Moreira      8751876.44
12                       Moura - ME      8979641.72
13                            Nunes      9738948.03
14            Ribeiro Sampaio Ltda.      6657374.14
15              Sampaio Viana Ltda.      7298637.36
16                           Santos      9617626.31
17                            Sousa      9794351.73
18                         Teixeira      6745646.45
19                           Vargas      7201384.53