In [4]:
# importa a biblioteca pandas e dá o apelido 'pd'
import pandas as pd  

# importa a biblioteca numpy e dá o apelido 'np'
import numpy as np

In [12]:
Delegacias = pd.read_csv('https://www.ispdados.rj.gov.br/Arquivos/BaseDPEvolucaoMensalCisp.csv',sep=';',encoding='latin1')
Delegacias

,cisp,mes,ano,mes_ano,aisp,risp,munic,mcirc,regiao,hom_doloso,...,cmp,cmba,ameaca,pessoas_desaparecidas,encontro_cadaver,encontro_ossada,pol_militares_mortos_serv,pol_civis_mortos_serv,registro_ocorrencias,fase
0,1,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,0,...,NaN,NaN,21,2,0,0,0,0,578,3
1,4,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,3,...,NaN,NaN,15,6,0,1,0,0,441,3
2,5,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,3,...,NaN,NaN,47,2,1,0,0,0,637,3
3,6,1,2003,2003m01,1,1,Rio de Janeiro,3304557,Capital,6,...,NaN,NaN,26,2,1,0,0,0,473,3
4,7,1,2003,2003m01,1,1,Rio de Janeiro,3304557,Capital,4,...,NaN,NaN,10,1,3,0,0,0,147,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36624,159,8,2025,2025m08,35,4,Cachoeiras de Macacu,3300803,Interior,1,...,5.0,0.0,16,0,0,0,0,0,148,2
36625,165,8,2025,2025m08,33,5,Mangaratiba,3302601,Interior,0,...,5.0,0.0,21,2,0,0,0,0,179,2
36626,166,8,2025,2025m08,33,5,Angra dos Reis,3300100,Interior,3,...,11.0,3.0,63,8,0,0,0,0,595,2
36627,167,8,2025,2025m08,43,5,Paraty,3303807,Interior,0,...,3.0,0.0,13,2,0,1,0,0,234,2
36628,168,8,2025,2025m08,28,5,Rio Claro,3304409,Interior,1,...,1.0,0.0,5,0,0,0,0,0,50,2

In [71]:
municipios_rj = [
    "Rio de Janeiro",
    "Belford Roxo",
    "Duque de Caxias",
    "Guapimirim",
    "Itaboraí",
    "Itaguaí",
    "Japeri",
    "Magé",
    "Maricá",
    "Mesquita",
    "Nilópolis",
    "Niterói",
    "Nova Iguaçu",
    "Paracambi",
    "Queimados",
    "São Gonçalo",
    "São João de Meriti",
    "Seropédica",
    "Tanguá",
    "Cachoeiras de Macacu",
    "Rio Bonito",
    "Petrópolis"
]

#04 Compare os outliers dos dois primeiros anos da atual gestão
com os dois primeiros anos da gestão anterior no que diz
respeito a estelionato na região metropolitana. O padrão de

manteve?

Alguma delegacia deixou de ser outlier? Alguma delegacia
passou a ser considerada outlier que anteriormente não era ?

In [131]:



gestao_atual = Delegacias[(Delegacias['munic'].isin(municipios_rj)) & (Delegacias['ano'].isin([2023, 2024]))]
gestao_atual

,cisp,mes,ano,mes_ano,aisp,risp,munic,mcirc,regiao,hom_doloso,...,cmp,cmba,ameaca,pessoas_desaparecidas,encontro_cadaver,encontro_ossada,pol_militares_mortos_serv,pol_civis_mortos_serv,registro_ocorrencias,fase
32245,1,1,2023,2023m01,5,1,Rio de Janeiro,3304557,Capital,0,...,5.0,0.0,12,2,0,0,0,0,772,3
32246,4,1,2023,2023m01,5,1,Rio de Janeiro,3304557,Capital,0,...,9.0,1.0,14,4,0,0,0,0,614,3
32247,5,1,2023,2023m01,5,1,Rio de Janeiro,3304557,Capital,1,...,14.0,1.0,30,4,0,0,0,0,1258,3
32248,6,1,2023,2023m01,4,1,Rio de Janeiro,3304557,Capital,2,...,2.0,2.0,19,3,0,0,0,0,360,3
32249,7,1,2023,2023m01,5,1,Rio de Janeiro,3304557,Capital,1,...,0.0,1.0,18,1,0,0,0,0,232,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35467,82,12,2024,2024m12,12,4,Maricá,3302700,Grande NiterÃ³i,2,...,11.0,0.0,115,5,0,0,0,0,1076,3
35483,105,12,2024,2024m12,26,7,Petrópolis,3303906,Interior,0,...,11.0,0.0,75,3,0,0,0,0,782,3
35484,106,12,2024,2024m12,26,7,Petrópolis,3303906,Interior,0,...,7.0,1.0,42,3,0,0,0,0,354,3
35492,119,12,2024,2024m12,35,4,Rio Bonito,3304300,Interior,1,...,0.0,0.0,20,0,0,0,0,0,178,3
35528,159,12,2024,2024m12,35,4,Cachoeiras de Macacu,3300803,Interior,1,...,1.0,0.0,27,2,0,0,0,0,137,3

In [134]:


gestao_atual_Agrupamento = gestao_atual.groupby(['cisp'])['estelionato'].sum().reset_index()
gestao_atual_Agrupamento

    cisp  estelionato
0      1         2146
1      4         1010
2      5         3011
3      6         1527
4      7          753
..   ...          ...
71    82         3498
72   105         3310
73   106         1466
74   119          501
75   159          458

[76 rows x 2 columns]

In [136]:


array_gestao_atual_grupamento = np.array(gestao_atual_Agrupamento["estelionato"])

# Mediana (valor central)
mediana_atual = np.median(array_gestao_atual_grupamento)
media_atual = np.mean(array_gestao_atual_grupamento)

# Quartis
q1_atual = np.percentile(array_gestao_atual_grupamento, 25)  # Primeiro quartil
q2_atual = np.percentile(array_gestao_atual_grupamento, 50)  # Terceiro quartil
q3_atual = np.percentile(array_gestao_atual_grupamento, 75)  # Terceiro quartil
distancia_atual = (media_atual - mediana_atual) / mediana_atual
iqr_atual = q3_atual - q1_atual
limite_superior_atual = q3_atual + (1.5*iqr_atual)
limite_inferior_atual = q1_atual - (1.5*iqr_atual)

print(f'media {media_atual}')
print(f'mediana {mediana_atual}')
print(f'distancia {distancia_atual*100}%')

media 2776.9605263157896
mediana 2251.0
distancia 23.365638663517974%

In [137]:




gestao_Anterior = Delegacias[(Delegacias['munic'].isin(municipios_rj)) & (Delegacias['ano'].isin([2019, 2020]))]
gestao_Anterior

,cisp,mes,ano,mes_ano,aisp,risp,munic,mcirc,regiao,hom_doloso,...,cmp,cmba,ameaca,pessoas_desaparecidas,encontro_cadaver,encontro_ossada,pol_militares_mortos_serv,pol_civis_mortos_serv,registro_ocorrencias,fase
25669,1,1,2019,2019m01,5,1,Rio de Janeiro,3304557,Capital,0,...,8.0,1.0,11,1,0,0,0,0,572,3
25670,4,1,2019,2019m01,5,1,Rio de Janeiro,3304557,Capital,1,...,15.0,10.0,12,2,1,0,0,0,625,3
25671,5,1,2019,2019m01,5,1,Rio de Janeiro,3304557,Capital,0,...,30.0,18.0,29,3,0,0,0,0,1095,3
25672,6,1,2019,2019m01,4,1,Rio de Janeiro,3304557,Capital,3,...,9.0,2.0,33,3,0,0,0,0,575,3
25673,7,1,2019,2019m01,5,1,Rio de Janeiro,3304557,Capital,1,...,0.0,0.0,9,0,0,0,0,0,147,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28891,82,12,2020,2020m12,12,4,Maricá,3302700,Grande NiterÃ³i,10,...,7.0,0.0,49,8,0,0,0,0,537,3
28907,105,12,2020,2020m12,26,7,Petrópolis,3303906,Interior,3,...,37.0,0.0,75,1,1,0,0,0,510,3
28908,106,12,2020,2020m12,26,7,Petrópolis,3303906,Interior,1,...,7.0,0.0,18,0,0,0,0,0,166,3
28916,119,12,2020,2020m12,35,4,Rio Bonito,3304300,Interior,0,...,5.0,1.0,17,1,0,0,0,0,124,3
28952,159,12,2020,2020m12,35,4,Cachoeiras de Macacu,3300803,Interior,0,...,2.0,0.0,14,1,0,0,0,0,90,3

In [138]:


gestao_Anterior_grupamento = gestao_Anterior.groupby(['cisp'])['estelionato'].sum().reset_index()
gestao_Anterior_grupamento

    cisp  estelionato
0      1         2560
1      4          417
2      5         1788
3      6          706
4      7          114
..   ...          ...
71    82          684
72   105         1083
73   106          223
74   119          124
75   159          151

[76 rows x 2 columns]

In [139]:


array_gestao_anterior_grupamento = np.array(gestao_Anterior_grupamento["estelionato"])

# Mediana (valor central)
mediana_anterior = np.median(array_gestao_anterior_grupamento)
media_anterior = np.mean(array_gestao_anterior_grupamento)

# Quartis
q1_anterior = np.percentile(array_gestao_anterior_grupamento, 25)  # Primeiro quartil
q2_anterior = np.percentile(array_gestao_anterior_grupamento, 50)  # Terceiro quartil
q3_anterior = np.percentile(array_gestao_anterior_grupamento, 75)  # Terceiro quartil
distancia_anterior = (media_anterior - mediana_anterior) / mediana_anterior
iqr_anterior = q3_anterior - q1_anterior
limite_superior_anterior = q3_anterior + (1.5*iqr_anterior)
limite_inferior_anterior = q1_anterior - (1.5*iqr_anterior)

print(f'media {media_anterior}')
print(f'mediana {mediana_anterior}')
print(f'distancia {distancia_anterior*100}%')

media 987.3815789473684
mediana 706.5
distancia 39.75676984393042%

In [142]:
Outliers_Anterior = gestao_Anterior_grupamento.loc[gestao_Anterior_grupamento['estelionato'] >= limite_superior_anterior]
Outliers_Anterior.sort_values(by='estelionato', ascending= False)

    cisp  estelionato
31    35         3592
12    16         3054

In [144]:
Outliers_atual = gestao_atual_Agrupamento.loc[gestao_atual_Agrupamento['estelionato'] >= limite_superior_anterior]
Outliers_atual.sort_values(by='estelionato', ascending= False)

    cisp  estelionato
31    35        10026
12    16         9665
28    32         9529
38    42         6433
56    64         5797
30    34         5442
46    54         4981
8     12         4718
15    19         4676
17    21         4500
25    29         4256
10    14         4142
51    59         4077
67    77         3923
32    36         3830
66    76         3768
5      9         3763
29    33         3559
71    82         3498
37    41         3475
6     10         3450
18    22         3426
72   105         3310
50    58         3266
44    52         3250
23    27         3169
33    37         3109
11    15         3029
2      5         3011