In [1]:
# importa a biblioteca pandas e dá o apelido 'pd'
import pandas as pd  

# importa a biblioteca numpy e dá o apelido 'np'
import numpy as np

In [2]:
# Importa os dados do arquivo 

df = pd.read_csv('https://www.ispdados.rj.gov.br/Arquivos/BaseDPEvolucaoMensalCisp.csv',delimiter=";", encoding="latin1")

# Exibe o conteúdo completo do DataFrame 'pesquisa' no console.
df.head()

,cisp,mes,ano,mes_ano,aisp,risp,munic,mcirc,regiao,hom_doloso,...,cmp,cmba,ameaca,pessoas_desaparecidas,encontro_cadaver,encontro_ossada,pol_militares_mortos_serv,pol_civis_mortos_serv,registro_ocorrencias,fase
0,1,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,0,...,NaN,NaN,21,2,0,0,0,0,578,3
1,4,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,3,...,NaN,NaN,15,6,0,1,0,0,441,3
2,5,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,3,...,NaN,NaN,47,2,1,0,0,0,637,3
3,6,1,2003,2003m01,1,1,Rio de Janeiro,3304557,Capital,6,...,NaN,NaN,26,2,1,0,0,0,473,3
4,7,1,2003,2003m01,1,1,Rio de Janeiro,3304557,Capital,4,...,NaN,NaN,10,1,3,0,0,0,147,3

In [3]:
municipios_baixada_fluminense = [
   "Duque de Caxias",
    "Nova Iguaçu",
    "São João de Meriti",
    "Belford Roxo",
    "Nilópolis",
    "Mesquita",
    "Queimados",
    "Japeri",
    "Magé",
    "Guapimirim",
    "Seropédica",
    "Itaguaí",
    "Paracambi"
]

In [4]:




municipios = df.loc[(df['munic'].isin(municipios_baixada_fluminense))]
municipios

,cisp,mes,ano,mes_ano,aisp,risp,munic,mcirc,regiao,hom_doloso,...,cmp,cmba,ameaca,pessoas_desaparecidas,encontro_cadaver,encontro_ossada,pol_militares_mortos_serv,pol_civis_mortos_serv,registro_ocorrencias,fase
38,48,1,2003,2003m01,24,3,Seropédica,3305554,Baixada Fluminense,4,...,NaN,NaN,28,0,1,0,0,0,139,3
39,50,1,2003,2003m01,24,3,Itaguaí,3302007,Baixada Fluminense,7,...,NaN,NaN,79,3,0,0,0,0,246,3
40,51,1,2003,2003m01,24,3,Paracambi,3303609,Baixada Fluminense,2,...,NaN,NaN,26,2,0,0,0,0,91,3
41,52,1,2003,2003m01,20,3,Nova Iguaçu,3303500,Baixada Fluminense,6,...,NaN,NaN,94,1,1,0,0,0,585,3
42,53,1,2003,2003m01,20,3,Mesquita,3302858,Baixada Fluminense,8,...,NaN,NaN,89,4,1,0,0,0,372,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36684,63,9,2025,2025m09,24,3,Japeri,3302270,Baixada Fluminense,4,...,16.0,1.0,25,2,1,0,0,0,271,2
36685,64,9,2025,2025m09,21,3,São João de Meriti,3305109,Baixada Fluminense,5,...,23.0,1.0,158,12,2,0,0,0,1817,2
36686,65,9,2025,2025m09,34,3,Magé,3302502,Baixada Fluminense,1,...,4.0,0.0,35,3,1,0,0,0,324,2
36687,66,9,2025,2025m09,34,3,Magé,3302502,Baixada Fluminense,0,...,10.0,0.0,111,9,0,0,0,0,616,2
36688,67,9,2025,2025m09,34,3,Guapimirim,3301850,Baixada Fluminense,2,...,6.0,0.0,42,1,0,0,0,0,306,2

In [5]:
df_baixada = municipios.groupby(['munic'])['aaapai'].sum().reset_index()
df_baixada

                 munic  aaapai
0         Belford Roxo  2595.0
1      Duque de Caxias  6239.0
2           Guapimirim   213.0
3              Itaguaí   882.0
4               Japeri   402.0
5                 Magé  1254.0
6             Mesquita  1219.0
7            Nilópolis   695.0
8          Nova Iguaçu  4106.0
9            Paracambi   367.0
10           Queimados   573.0
11          Seropédica   309.0
12  São João de Meriti  2956.0

In [6]:
q3 = np.percentile(df_baixada["aaapai"], 75)
print(f'Terceiro quartil (Q3) = {q3}')

Terceiro quartil (Q3) = 2595.0

In [7]:
df_final = df_baixada.loc[df_baixada["aaapai"] > q3]
df_final

                 munic  aaapai
1      Duque de Caxias  6239.0
8          Nova Iguaçu  4106.0
12  São João de Meriti  2956.0

In [8]:
df_final.to_csv('Apreensões_menores.csv', sep=";", index=  False)

In [9]:
array_df_baixada = np.array(df_baixada["aaapai"])

# Mediana (valor central)
mediana_anterior = np.median(array_df_baixada)
media_anterior = np.mean(array_df_baixada)

# Quartis
q1_anterior = np.percentile(array_df_baixada, 25)  # Primeiro quartil
q2_anterior = np.percentile(array_df_baixada, 50)  # Terceiro quartil
q3_anterior = np.percentile(array_df_baixada, 75)  # Terceiro quartil
distancia_anterior = (media_anterior - mediana_anterior) / mediana_anterior
iqr_anterior = q3_anterior - q1_anterior
limite_superior_total = q3_anterior + (1.5*iqr_anterior)
limite_inferior_total = q1_anterior - (1.5*iqr_anterior)

print(f'media {media_anterior}')
print(f'mediana {mediana_anterior}')
print(f'distancia {distancia_anterior*100}%')

media 1677.6923076923076
mediana 882.0
distancia 90.2145473574045%

In [12]:
dados_array = np.array(array_df_baixada)

media = np.mean(dados_array)

variancia = np.var(dados_array)

desvio_padrao = np.std(dados_array)

coeficiente_variacao = (desvio_padrao/ media)*100

distancia_variancia = (variancia / (media **2))*100

print("Média:", media)

print("Variância:", variancia)

print("Desvio padrão:", desvio_padrao)

print("Coeficiente de variação:", coeficiente_variacao)

print("Distância da variância em relação à média:", distancia_variancia)

Média: 1677.6923076923076
Variância: 3057749.7514792904
Desvio padrão: 1748.6422594342419
Coeficiente de variação: 104.22902050731382
Distância da variância em relação à média: 108.63688715914046

In [10]:

Outliers_superior = df_final.loc[df_final['aaapai'] >= limite_superior_total]
print(Outliers_superior)

             munic  aaapai
1  Duque de Caxias  6239.0

In [11]:
Outliers_superior.to_csv('Outliers_superior _Apreensões.csv', sep=";", index=  False)