In [1]:
# importa a biblioteca pandas e dá o apelido 'pd'
import pandas as pd  

# importa a biblioteca numpy e dá o apelido 'np'
import numpy as np

In [11]:
# Importa os dados do arquivo 

df = pd.read_csv('https://www.ispdados.rj.gov.br/Arquivos/BaseDPEvolucaoMensalCisp.csv',delimiter=";", encoding="latin1")

# Exibe o conteúdo completo do DataFrame 'pesquisa' no console.
df.head()

,cisp,mes,ano,mes_ano,aisp,risp,munic,mcirc,regiao,hom_doloso,...,cmp,cmba,ameaca,pessoas_desaparecidas,encontro_cadaver,encontro_ossada,pol_militares_mortos_serv,pol_civis_mortos_serv,registro_ocorrencias,fase
0,1,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,0,...,NaN,NaN,21,2,0,0,0,0,578,3
1,4,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,3,...,NaN,NaN,15,6,0,1,0,0,441,3
2,5,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,3,...,NaN,NaN,47,2,1,0,0,0,637,3
3,6,1,2003,2003m01,1,1,Rio de Janeiro,3304557,Capital,6,...,NaN,NaN,26,2,1,0,0,0,473,3
4,7,1,2003,2003m01,1,1,Rio de Janeiro,3304557,Capital,4,...,NaN,NaN,10,1,3,0,0,0,147,3

In [13]:
municipios_baixada_fluminense = [
   "Duque de Caxias",
    "Nova Iguaçu",
    "São João de Meriti",
    "Belford Roxo",
    "Nilópolis",
    "Mesquita",
    "Queimados",
    "Japeri",
    "Magé",
    "Guapimirim",
    "Seropédica",
    "Itaguaí",
    "Paracambi"
]

In [22]:




municipios = df.loc[(df['munic'].isin(municipios_baixada_fluminense))]
municipios

,cisp,mes,ano,mes_ano,aisp,risp,munic,mcirc,regiao,hom_doloso,...,cmp,cmba,ameaca,pessoas_desaparecidas,encontro_cadaver,encontro_ossada,pol_militares_mortos_serv,pol_civis_mortos_serv,registro_ocorrencias,fase
38,48,1,2003,2003m01,24,3,Seropédica,3305554,Baixada Fluminense,4,...,NaN,NaN,28,0,1,0,0,0,139,3
39,50,1,2003,2003m01,24,3,Itaguaí,3302007,Baixada Fluminense,7,...,NaN,NaN,79,3,0,0,0,0,246,3
40,51,1,2003,2003m01,24,3,Paracambi,3303609,Baixada Fluminense,2,...,NaN,NaN,26,2,0,0,0,0,91,3
41,52,1,2003,2003m01,20,3,Nova Iguaçu,3303500,Baixada Fluminense,6,...,NaN,NaN,94,1,1,0,0,0,585,3
42,53,1,2003,2003m01,20,3,Mesquita,3302858,Baixada Fluminense,8,...,NaN,NaN,89,4,1,0,0,0,372,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36547,63,8,2025,2025m08,24,3,Japeri,3302270,Baixada Fluminense,0,...,5.0,1.0,30,3,0,0,0,0,256,2
36548,64,8,2025,2025m08,21,3,São João de Meriti,3305109,Baixada Fluminense,7,...,23.0,0.0,168,17,2,0,0,0,2040,2
36549,65,8,2025,2025m08,34,3,Magé,3302502,Baixada Fluminense,1,...,5.0,0.0,40,2,0,0,0,0,278,2
36550,66,8,2025,2025m08,34,3,Magé,3302502,Baixada Fluminense,3,...,11.0,0.0,82,4,0,0,0,0,631,2
36551,67,8,2025,2025m08,34,3,Guapimirim,3301850,Baixada Fluminense,1,...,10.0,0.0,26,1,0,0,0,0,266,2

In [28]:
df_baixada = municipios.groupby(['munic'])['aaapai'].sum().reset_index()
df_baixada

                 munic  aaapai
0         Belford Roxo  2584.0
1      Duque de Caxias  6233.0
2           Guapimirim   213.0
3              Itaguaí   881.0
4               Japeri   402.0
5                 Magé  1251.0
6             Mesquita  1218.0
7            Nilópolis   693.0
8          Nova Iguaçu  4098.0
9            Paracambi   366.0
10           Queimados   573.0
11          Seropédica   309.0
12  São João de Meriti  2953.0

In [30]:
q3 = np.percentile(df_baixada["aaapai"], 75)
print(f'Terceiro quartil (Q3) = {q3}')

Terceiro quartil (Q3) = 2584.0

In [31]:
df_final = df_baixada.loc[df_baixada["aaapai"] > q3]
df_final

                 munic  aaapai
1      Duque de Caxias  6233.0
8          Nova Iguaçu  4098.0
12  São João de Meriti  2953.0

In [32]:
df_final.to_csv('nome_1.csv', sep=";", index=  False)