In [108]:
# importa a biblioteca pandas e dá o apelido 'pd'
import pandas as pd  

# importa a biblioteca numpy e dá o apelido 'np'
import numpy as np

In [109]:
# Importa os dados do arquivo 

df = pd.read_csv('https://www.ispdados.rj.gov.br/Arquivos/BaseDPEvolucaoMensalCisp.csv',delimiter=";", encoding="latin1")

# Exibe o conteúdo completo do DataFrame 'pesquisa' no console.
df.head()

,cisp,mes,ano,mes_ano,aisp,risp,munic,mcirc,regiao,hom_doloso,...,cmp,cmba,ameaca,pessoas_desaparecidas,encontro_cadaver,encontro_ossada,pol_militares_mortos_serv,pol_civis_mortos_serv,registro_ocorrencias,fase
0,1,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,0,...,NaN,NaN,21,2,0,0,0,0,578,3
1,4,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,3,...,NaN,NaN,15,6,0,1,0,0,441,3
2,5,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,3,...,NaN,NaN,47,2,1,0,0,0,637,3
3,6,1,2003,2003m01,1,1,Rio de Janeiro,3304557,Capital,6,...,NaN,NaN,26,2,1,0,0,0,473,3
4,7,1,2003,2003m01,1,1,Rio de Janeiro,3304557,Capital,4,...,NaN,NaN,10,1,3,0,0,0,147,3

In [110]:
municipios_regiao_dos_lagos = [
    "Araruama",
    "Armação dos Búzios",
    "Arraial do Cabo",
    "Cabo Frio",
    "Iguaba Grande",
    "São Pedro da Aldeia",
    "Saquarema"
]

In [111]:

regiao_lagos = df.loc[(df['munic'].isin(municipios_regiao_dos_lagos))]
regiao_lagos

,cisp,mes,ano,mes_ano,aisp,risp,munic,mcirc,regiao,hom_doloso,...,cmp,cmba,ameaca,pessoas_desaparecidas,encontro_cadaver,encontro_ossada,pol_militares_mortos_serv,pol_civis_mortos_serv,registro_ocorrencias,fase
88,118,1,2003,2003m01,25,4,Araruama,3300209,Interior,3,...,NaN,NaN,35,2,0,0,0,0,301,3
94,124,1,2003,2003m01,25,4,Saquarema,3305505,Interior,2,...,NaN,NaN,30,1,1,0,0,0,177,3
95,125,1,2003,2003m01,25,4,São Pedro da Aldeia,3305208,Interior,4,...,NaN,NaN,40,0,1,0,0,0,228,3
97,127,1,2003,2003m01,25,4,Armação dos Búzios,3300233,Interior,11,...,NaN,NaN,24,2,2,0,0,0,269,3
99,129,1,2003,2003m01,25,4,Iguaba Grande,3301876,Interior,0,...,NaN,NaN,10,0,0,0,0,0,63,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36594,125,8,2025,2025m08,25,4,São Pedro da Aldeia,3305208,Interior,3,...,10.0,1.0,33,1,0,0,0,0,321,2
36595,126,8,2025,2025m08,25,4,Cabo Frio,3300704,Interior,8,...,23.0,0.0,94,9,0,0,0,0,1159,2
36596,127,8,2025,2025m08,25,4,Armação dos Búzios,3300233,Interior,0,...,3.0,0.0,16,2,0,0,0,0,283,2
36598,129,8,2025,2025m08,25,4,Iguaba Grande,3301876,Interior,0,...,3.0,0.0,18,1,0,0,0,0,157,2
36600,132,8,2025,2025m08,25,4,Arraial do Cabo,3300258,Interior,0,...,2.0,0.0,10,1,0,0,0,0,156,2

In [112]:
violencia = [
    "hom_doloso",
    "lesao_corp_morte",
    "latrocinio",
    "cvli",
    "hom_por_interv_policial",
    "letalidade_violenta",
    "tentat_hom",
    "lesao_corp_dolosa",
    "estupro"
]

In [113]:
crimes_lagos = regiao_lagos[["munic","hom_doloso",
    "lesao_corp_morte",
    "latrocinio",
    "cvli",
    "hom_por_interv_policial",
    "letalidade_violenta",
    "tentat_hom",
    "lesao_corp_dolosa",
    "estupro",]] 
crimes_lagos

,munic,hom_doloso,lesao_corp_morte,latrocinio,cvli,hom_por_interv_policial,letalidade_violenta,tentat_hom,lesao_corp_dolosa,estupro
88,Araruama,3,0,0,3,0,3,0,61,4
94,Saquarema,2,0,0,2,0,2,1,19,3
95,São Pedro da Aldeia,4,0,0,4,0,4,4,51,0
97,Armação dos Búzios,11,0,0,11,0,11,2,42,2
99,Iguaba Grande,0,0,0,0,0,0,0,7,0
...,...,...,...,...,...,...,...,...,...,...
36594,São Pedro da Aldeia,3,0,0,3,0,3,2,21,7
36595,Cabo Frio,8,0,0,8,1,9,2,76,19
36596,Armação dos Búzios,0,0,0,0,0,0,2,19,3
36598,Iguaba Grande,0,0,0,0,0,0,1,13,4
36600,Arraial do Cabo,0,0,0,0,0,0,0,15,3

In [117]:
crimes_lagos["crimes_violentos"] = crimes_lagos["hom_doloso"].astype(int) + crimes_lagos["lesao_corp_morte"].astype(int) + crimes_lagos["latrocinio"].astype(int) + crimes_lagos["cvli"].astype(int) + crimes_lagos["hom_por_interv_policial"].astype(int) + crimes_lagos["letalidade_violenta"].astype(int) + crimes_lagos["tentat_hom"].astype(int) + crimes_lagos["lesao_corp_dolosa"].astype(int) + crimes_lagos["estupro"].astype(int)
crimes_lagos

C:\Users\jose.flor\AppData\Local\Temp\ipykernel_29320\937033476.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  crimes_lagos["crimes_violentos"] = crimes_lagos["hom_doloso"].astype(int) + crimes_lagos["lesao_corp_morte"].astype(int) + crimes_lagos["latrocinio"].astype(int) + crimes_lagos["cvli"].astype(int) + crimes_lagos["hom_por_interv_policial"].astype(int) + crimes_lagos["letalidade_violenta"].astype(int) + crimes_lagos["tentat_hom"].astype(int) + crimes_lagos["lesao_corp_dolosa"].astype(int) + crimes_lagos["estupro"].astype(int)

,munic,hom_doloso,lesao_corp_morte,latrocinio,cvli,hom_por_interv_policial,letalidade_violenta,tentat_hom,lesao_corp_dolosa,estupro,crimes_violentos
88,Araruama,3,0,0,3,0,3,0,61,4,74
94,Saquarema,2,0,0,2,0,2,1,19,3,29
95,São Pedro da Aldeia,4,0,0,4,0,4,4,51,0,67
97,Armação dos Búzios,11,0,0,11,0,11,2,42,2,79
99,Iguaba Grande,0,0,0,0,0,0,0,7,0,7
...,...,...,...,...,...,...,...,...,...,...,...
36594,São Pedro da Aldeia,3,0,0,3,0,3,2,21,7,39
36595,Cabo Frio,8,0,0,8,1,9,2,76,19,123
36596,Armação dos Búzios,0,0,0,0,0,0,2,19,3,24
36598,Iguaba Grande,0,0,0,0,0,0,1,13,4,18
36600,Arraial do Cabo,0,0,0,0,0,0,0,15,3,18